### ISSUE TITLE
smbclient missing

### ISSUE THREAD

**Issue by luisjira** [docker-library/owncloud#94] opened 2017-11-20 18:05 UTC
When enabling external storage support I get the error: 
`Note: "smbclient" is not installed. Mounting of SMB / CIFS, SMB / CIFS using OC login is not possible. Please ask your system administrator to install it.`

**Comment by tianon** [comment] 2017-11-20 18:35
Duplicate of #79.

**Closed as completed by tianon** 2017-11-20 18:35 UTC
